project:
  type: website
  output-dir: docs/

website:
  title: "website for kartik sirwani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



